name: my first workflow

on: push

jobs:
  first_job:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: list and read files
        run: |
          echo "This is my Github Workflow"
          ls -ltra
          cat README.md

      - name: Generate ASCII values
        run: cowsay -f cow "cow is coming please move" >> cow.txt      
        



