name: Generate ASCII Artwork

on:
  push

jobs:
  asciijobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Execute shell scripting
        run: /.github/workflows/ascii-script.sh

      - name: List Repo files
        run: ls -la
